###############################################################################
#                                   PROD VARIABLES                            #
# Only include non Secure variables, for secure variables add it in Pipeline
# with 'secrets' enabled
###############################################################################

variables:

    azureSubscription: 'Azure DevOps - Enterprise Data Production'
    KeyVaultName: 'kv-ea2-edaa-apis'

    Location01: 'East US 2'
    Location02: 'Central US'

    appName01: 'fa-ea2-edaa-apis-product'
    appName02: 'fa-cn-edaa-apis-product'
#AppSetting Variables
    CosmosURL: $(CosmosDB-URL)
    CosmosWriteKey: $(CosmosDB-PrimaryWriteKey)
    CosmosReadKey: $(CosmosDB-PrimaryReadKey)
